services:
  backend:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - "DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}"
      - "DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}"
      - "DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}"
      - "DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}"
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "NEXT_PUBLIC_URL=${NEXT_PUBLIC_URL}"
    command: sh /app/start.sh
    depends_on:
      - db

  db:
    image: postgres:17.5-alpine3.21
    ports:
        - "5432:5432"
    environment:
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
